- name: configure payment component
  hosts: payment
  become: yes
  tasks:
  - name: install python3 packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
    loop:
    - python3 
    - gcc 
    - python3-devel 

  
  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download payment code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
      dest: /tmp/payment.zip

  - name: extract payment code
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: install depedencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copy payment service repo
    ansible.builtin.copy:
      name: payment.repo
      dest: /etc/systemd/system/payment.service

  - name: systemctl daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  

  - name: start and enable payment
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes
